### ISSUE TITLE
Demo app is unavailable

### ISSUE THREAD

**Issue by pBorak** [thoughtbot/superglue#24]
In Superglue's guide, there's a demo app (https://thoughtbot.github.io/superglue/#/demo), unfortunately, I found that the link is not working - https://github.com/thoughtbot/select-your-own-seat

**Comment by jho406** [comment]
Sorry about that! I just released a new version along with updated docs. You can find the demo app [here](https://github.com/thoughtbot/select-your-own-seat-superglue).
