### ISSUE TITLE
Migrate superglue from CircleCI to github

### ISSUE THREAD

**Issue by jho406** [thoughtbot/superglue#42]
Superglue currently use CircleCI. I'd like to migrate and use github actions to test against rails main (to run weekly), 70, and 71. Today both `form_props` and `props_template`  all use github actions. Here’s a build yaml used by props_template to get us started: [https://github.com/thoughtbot/props_template/blob/main/.github/workflows/build.yml](https://github.com/thoughtbot/props_template/blob/main/.github/workflows/build.yml "smartCard-inline")

**Comment by stefannibrasil** [comment]
I was going to work on this but realized the workflows already exists. Anything else left from this issue?

**Comment by jho406** [comment]
Sorry about that @stefannibrasil! I did a PR for this on https://github.com/thoughtbot/superglue/pull/41. As it turns out the run works well for everything but rails main. I suspect that its a bin/stub issue (i'm using rails from github instead of bundle), but haven't been able to diagnose properly.

**Comment by jho406** [comment]
Feel free to take a look at that failure. The other thing I wanted to do was to remove that CircleCi badge on the readme.

**Comment by stefannibrasil** [comment]
Sounds good! If I finish my task today, I will circle back on the error. In that note, is there a reason why you're using rails `main` branch instead of the latest stable release? I find it a bit dangerous to use rails main branch, curious to see why it's being used here.

**Comment by jho406** [comment]
Its only used for testing. If CI is red when targeting rails main, it a sign that the project has to begin preparing for possible breaking changes when used on the next version of rails.

**Comment by jho406** [comment]
I also created a story for the badge removal. https://github.com/thoughtbot/superglue/issues/50

**Comment by stefannibrasil** [comment]
I had some time today to get more context on the errors. I updated the acceptance test to print out the errors to make debugging easier. It looks like we're running into issues with sqlite for the tests and not finding the Gemfile in the acceptance step:

https://github.com/thoughtbot/superglue/actions/runs/8792334725

I will keep investigating this but I have limited time this week.

**Comment by jho406** [comment]
No worries! @stefannibrasil. Thanks so much for contributing. That sqllte issue popped out from no where.  I also have avail this friday to fix the errors.

**Comment by stefannibrasil** [comment]
The Sqlite3 error has been fixed by [pinning its version to "~> 1.4"](https://github.com/rails/rails/pull/51591/files). Still finding out what's happening with the Gemfile in the `superglue_rails` directory. At least the errors are being printed out:

https://github.com/thoughtbot/superglue/actions/runs/8808234708/job/24176916935

Was CI running before on circle ci? 🤔

**Comment by stefannibrasil** [comment]
hey @jho406 opened a PR to run Rails main on a schedule instead of at every commit/push: https://github.com/thoughtbot/superglue/pull/58
