### ISSUE TITLE
Add typescript support  - Part II 

### ISSUE THREAD

**Issue by jho406** [thoughtbot/superglue#43]
All of superglue is written in ES6. For developers working with React, typescript has been a valuable tool to have. It would improve the developer experience if superglue was converted to Typescript.

In this story, we should add type annotations to every function in superglue and move from gradual typing to something a bit more strict.

### Thoughts

Not all features of superglue can be converted to typescript.

1. [digging](https://thoughtbot.github.io/superglue/#/traversal-guide "‌") is a feature that make it easy to create medium effort interactivity, but it works off of key paths (http://xyz.com/posts/?props_at=header.notifications)
2. Superglue also comes with UJS helpers, for example: [using placeholders](https://thoughtbot.github.io/superglue/#/navigation?id=placeholders "‌"). Not sure what the best way to type this is.

Regardless, typing what we can is still a great step forward.

**Comment by stefannibrasil** [comment]
This task can be broken down into:

1 - add TypeScript first
2 - then we should be good to work on the other tasks mentioned here

**Comment by johncardiologs** [comment]
Hi! I prototyped adding Typescript at RailsConf 2024, PR here: https://github.com/thoughtbot/superglue/pull/60

I've mostly been trying to follow this [JS -> TS Migration guide](https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html) -- still new to this!

**Comment by jho406** [comment]
Closing as we've fully moved  superglue.js to typescript. Thanks for giving this the start that it needed @johncardiologs
