### ISSUE TITLE
Add an ERB Link exception

### ISSUE THREAD

**Issue by jho406** [thoughtbot/superglue#52]
The initial state generated by superglue_rails is already properly escaped json and can be marked as html_safe. But erblint may call that line out and recommend calling `to_json` before `html_safe`. We could add something like the below, or add some documentation on how to use with ERB lint.
 
```
<script type="text/javascript">
  window.SUPERGLUE_INITIAL_PAGE_STATE=<%= initial_state.html_safe %>;<%# erblint:disable ErbSafety %>
</script>
```

**Comment by jp524** [comment]
I'd like to work on this!
